### PR TITLE
FCDO-595: Remove staff training day text

### PR DESCRIPTION
**Pull request by simonmoore100**

### CODE REVIEW

**Comment by simonmoore100** [comment]
DON'T MERGE UNTIL MONDAY 11 APRIL

**Comment by simonmoore100** [comment]
DON'T MERGE UNTIL MONDAY 11 APRIL

**Review by benjamindi96k — APPROVED** [review]
Will LGTM on Mon 11th April

**Review by benjamindi96k — APPROVED** [review]
LGTM

**Pull request merged**
